name: Metrics
on:
  schedule: [{cron: "0 0 19 * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: WanderLanz/metrics@master
        with:
          filename: metrics-header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: WanderLanz
          template: classic
          base: header
          config_timezone: UTC
          config_display: regular
      - uses: WanderLanz/metrics@master
        with:
          filename: metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: WanderLanz
          template: classic
          base: ""
          config_timezone: UTC
          config_display: regular
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 91
          plugin_languages_recent_load: 500
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
